export { default as RestQuery } from './components/RestQuery/RestQuery.vue'
export { default as RestMutation } from './components/RestMutation/RestMutation.vue'
export { default as RestMutationFn } from './components/RestMutationFn/RestMutationFn.vue'
export { default as GraphqlQuery } from './components/GraphqlQuery/GraphqlQuery.vue'
export { default as GraphqlMutation } from './components/GraphqlMutation/GraphqlMutation.vue'
